scaling:
  replicaCount: 2

image:
  repository: nginxdemos/hello:latest
  pullPolicy: Always # IfNotPresent

service:
  type: LoadBalancer # LoadBalancer / ClusterIP / NodePort / ExternalName
  port: 80
  exposePort: 30080 # by siddhu expose to node
  internalPort: 80 # by siddhu Internal exposed within the pod
  targetPort: 80 # by siddhu App server listening on this port
