scaling:
  replicaCount: 4

image:
  repository: nginxdemos/hello:latest
  pullPolicy: Always # IfNotPresent

service:
  type: LoadBalancer # LoadBalancer / ClusterIP / NodePort / ExternalName
  port: 80
  exposePort: 30080 # expose to node
  internalPort: 80 # Internal exposed within the pod
  targetPort: 80 # App server listening on this port
