apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Chart.Name }}-helm
  labels:
    helm.sh/chart: {{ .Chart.Name }}-helm
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex, nofollow";
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-methods: 'GET, OPTIONS'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
spec:
  tls:
    - hosts:
        - chart-example.local
      secretName: ingress-{{ .Chart.Name }}-tls
  rules:
    - host: chart-example.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ingress-{{ .Chart.Name }}-helm
                port:
                  number: {{ .Values.service.port }}
