apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}-helm
  labels:
    env: prod
    owner: Maksim.E.Sorokin
    helm.sh/chart: deployment-{{ .Chart.Name }}-helm-{{ .Release.Name }}-labels
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-helm-{{ .Release.Name }}-match-labels
