apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}-helm
  labels:
    env: prod
    owner: Maksim.E.Sorokin
    app: service-{{ .Chart.Name }}-helm
    app.kubernetes.io/instance: service-{{ .Chart.Name }}-helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: service-{{ .Chart.Name }}-http
  selector:
    run: service-{{ .Chart.Name }}-helm
